### ISSUE TITLE
Permission Denied when cloning repo

### ISSUE THREAD

**Issue by sw00d** [klazuka/example-elm-hot-webpack#3]
Not sure if I'm missing something here but when I run this I get an error:

$ git clone git@github.com:simonh1000/elm-webpack-starter.git new-project 

Cloning into 'new-project'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Any ideas?

**Comment by klazuka** [comment]
try using an HTTPS url:
```
git clone https://github.com/simonh1000/elm-webpack-starter.git
```
